package com.norus.apibluebook.repositories

import com.norus.apibluebook.entities.TemplateChallengeQuestionEntity
import org.springframework.data.repository.reactive.ReactiveCrudRepository
import org.springframework.stereotype.Repository

@Repository
interface TemplateChallengeQuestionRepository : ReactiveCrudRepository<TemplateChallengeQuestionEntity, Long>