spring:
  profiles: dev
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres?schema=api
    driverClassName: org.postgresql.Driver
    user: postgres
    password: postgres
    change-log: classpath:/db/changelogs/db.changelog-master.xml
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=api
    username: postgres
    password: postgres

logging:
  level:
    liquibase: INFO