spring:
  liquibase:
    enabled: false
    change-log: classpath:/db/changelogs/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:./data/db
    username: sa
    password:
    driverClassName: org.h2.Driver
  config:
    activate:
      on-profile: dev