spring:
  profiles: dev
  liquibase:
    enabled: true
    change-log: classpath:/db/changelogs/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver