spring:
  profiles: dev
  liquibase:
    enabled: true
    change-log: classpath:/db/changelogs/db.changelog-master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/blue_book?ssl=false
    username: root
    password: root