create table question (
  id bigint not null generated by default as identity,
  identifier varchar(60) not null,
  content varchar(1000) not null,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null,
  primary key (id)
);

create table answer (
  id bigint not null generated by default as identity,
  id_question bigint not null,
  content varchar(600) not null,
  correct tinyint not null default 0,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null,
  primary key (id)
);

create table template_challenge (
  id bigint not null generated by default as identity,
  name varchar(120) not null,
  description varchar(360) not null,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null,
  primary key (id)
);

create table template_challenge_question (
  id bigint not null generated by default as identity,
  id_template_challenge bigint not null,
  id_question bigint not null,
  order smallint not null,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null,
  primary key (id),
  unique (
    id,
    id_question,
    order
  ),
  unique (
    id_template_challenge,
    id_question
  )
);

create table challenge (
  id bigint not null generated by default as identity,
  id_template_challenge bigint not null,
  id_question bigint not null,
  reference_code varchar(30) not null,
  started tinyint not null default 0,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null,
  finished_at timestamp null,
  primary key (id),
  constraint idx_unique_reference_code
    unique (reference_code)
);

create table challenge_answer (
  id bigint not null generated by default as identity,
  id_challenge bigint not null,
  id_question bigint not null,
  nickname varchar(255) not null,
  right tinyint not null default 0,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null,
  primary key (id)
);
